### PR TITLE
add sslcontext support

### PR DESCRIPTION
**Pull request by grongierisc**

### CODE REVIEW

**Review by daimor — APPROVED** [review]

**Comment by daimor** [comment]
That's very interesting, I've released 0.2.0, could you provide an example of how it can be used? I've no idea ))

**Comment by grongierisc** [comment]
you have to have an iris server with super server with SSL/TLS enable : 

https://docs.intersystems.com/iris20223/csp/docbook/Doc.View.cls?KEY=GTLS_superserver

To generate a key pair : 

```bash
openssl req -x509 -nodes -days 1 -newkey rsa:2048 -subj /CN=* -keyout /irisdev/app/server.key -out /irisdev/app/server.crt
```

Use certificate to connect : 

```python
python3 -m irissqlcli iris://SuperUser:SYS@localhost:33782/USER -c server.crt
```

Initial implementation, more testing has to be done.

**Comment by grongierisc** [comment]
image

seems to be ok

**Comment by grongierisc** [comment]
BTW : it works out for the box for sqlalchemy : 

```python
from sqlalchemy import create_engine

import ssl

sslcontext = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH,cafile="CA.cer")

engine = create_engine('iris://SuperUser:Password@localhost:1972/FHIRDB',connect_args={'sslcontext': sslcontext})
```

**Pull request merged**
